# Netlify Configuration for GHC Digital Twin

[build]
  command = "npm run build"
  publish = "frontend/.next"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "nft"