name: Deploy Digital Twin to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Create deployment structure
      run: |
        # Ensure main index.html exists
        if [ ! -f "index.html" ]; then
          echo "ERROR: index.html not found!"
          exit 1
        fi
        
        # Validate HTML file
        if ! grep -q "Green Hill Canarias" index.html; then
          echo "WARNING: index.html may be corrupted"
        fi
        
        # Create assets directory if it doesn't exist
        mkdir -p assets
        
        # Copy any additional HTML files
        for file in index_*.html; do
          if [ -f "$file" ]; then
            cp "$file" assets/
          fi
        done
        
        # Create basic 404 page
        cat > 404.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>404 - GHC Digital Twin</title>
            <script src="https://cdn.tailwindcss.com"></script>
        </head>
        <body class="bg-gray-100 min-h-screen flex items-center justify-center">
            <div class="text-center">
                <h1 class="text-6xl font-bold text-gray-800 mb-4">404</h1>
                <p class="text-xl text-gray-600 mb-8">Page not found</p>
                <a href="/" class="bg-green-600 text-white px-6 py-3 rounded-lg hover:bg-green-700">
                    Return Home
                </a>
            </div>
        </body>
        </html>
        EOF

        # Create robots.txt
        cat > robots.txt << 'EOF'
        User-agent: *
        Allow: /
        
        Sitemap: https://zakibaydoun.github.io/GHC-DigitalTwin-Production/sitemap.xml
        EOF

        # Create sitemap.xml
        cat > sitemap.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
          <url>
            <loc>https://zakibaydoun.github.io/GHC-DigitalTwin-Production/</loc>
            <lastmod>2024-01-01T00:00:00+00:00</lastmod>
            <priority>1.0</priority>
          </url>
        </urlset>
        EOF

    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4