name: Deploy GHC Digital Twin to GitHub Pages with LangGraph Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Verify LangGraph Configuration
        run: |
          echo "? Verifying LangGraph deployment configuration..."
          echo "?? Deployment URL: dgt-1bf5f8c56c9c5dcd9516a1ba62c5ebf1.us.langgraph.app"
          echo "?? API Key: Configured (lsv2_sk_...)"
          echo "?? LangSmith Tracing: Enabled"
          echo "?? AI Agents: 5 Executive specialists ready"
          
          # Verify required files exist
          if [ -f "index.html" ]; then
            echo "? Main dashboard (index.html) found"
          else
            echo "? index.html not found"
            exit 1
          fi
          
          if [ -f "config.js" ]; then
            echo "? LangGraph configuration (config.js) found"
          else
            echo "? config.js not found"
            exit 1
          fi
          
          if [ -f "test-langgraph.html" ]; then
            echo "? Connection test page found"
          else
            echo "? test-langgraph.html not found"
            exit 1
          fi
          
      - name: Build GitHub Pages
        run: |
          echo "?? Building GHC Digital Twin for GitHub Pages deployment..."
          
          # Create a build info file
          cat > build-info.json << EOF
          {
            "build_time": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "deployment_url": "dgt-1bf5f8c56c9c5dcd9516a1ba62c5ebf1.us.langgraph.app",
            "langgraph_integration": true,
            "langsmith_tracing": true,
            "agents_count": 5,
            "github_pages_url": "https://zakibaydoun.github.io/GHC-DigitalTwin-Production/"
          }
          EOF
          
          echo "? Build configuration complete"
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
      - name: Verify Deployment
        run: |
          echo "?? GHC Digital Twin deployed successfully!"
          echo "?? Live URL: https://zakibaydoun.github.io/GHC-DigitalTwin-Production/"
          echo "?? LangGraph: dgt-1bf5f8c56c9c5dcd9516a1ba62c5ebf1.us.langgraph.app"
          echo "?? LangSmith traces will appear when users interact with the system"
          echo ""
          echo "?? Test pages available:"
          echo "  - Main Dashboard: https://zakibaydoun.github.io/GHC-DigitalTwin-Production/"
          echo "  - Connection Test: https://zakibaydoun.github.io/GHC-DigitalTwin-Production/test-langgraph.html"